name: 'Free the Data'
email: freethedataproject@gmail.com
description: 'A project.'
logo: 'assets/images/logo.svg'
favicon: 'assets/images/logo.svg'
baseurl: ""

include: ["_pages"]

permalink: /:title/

plugins:
  - jekyll-feed

sass:
  style: compact # possible values: nested expanded compact compressed

# Syntax
markdown: kramdown
highlighter: rouge


collections:
  data101:
    output: true
  resources:
    output: true
  projects:
    output: true 

# Paginate
paginate: 10

# Exclude from processing.

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
